workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      groups:
        - FIREBASE # <-- Includes FIREBASE_SERVICE_ACCOUNT
        - GOOGLE # <-- Includes GOOGLE_SERVICES_JSON
      vars:
        CM_KEYSTORE_PATH: /tmp/keystore.keystore
        PACKAGE_NAME: 'io.codemagic.marijanapp' # <-- Put your package name here e.g. "io.codemagic.flutteryaml"
        GOOGLE_PLAY_TRACK: 'alpha' # <-- Any default or custom track that is not in ‘draft’ status
      android_signing:
        - marijan_android_keystore # <-- includes CM_KEYSTORE, CM_KEYSTORE_PASSWORD, CM_KEY_PASSWORD, CM_KEY_ALIAS
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Load Firebase configuration
        script: | 
          #!/usr/bin/env sh
          set -e # exit on first failed command
          echo $GOOGLE_SERVICES_JSON > $CM_BUILD_DIR/android/app/google-services.json
    
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Build APK with Flutter
        script: |
          cd . && flutter build apk --release --build-name=1.0.2 --build-number=3
    artifacts:
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: 1:715058820192:android:f0c493bfe91a0193a1ff05
          groups:
            - androidTesters
          artifact_type: 'apk'
